alter table admins add constraint UKmi8vkhus4xbdbqcac2jm4spvd unique (username);
alter table admins add constraint UK47bvqemyk6vlm0w7crc3opdd4 unique (email);
alter table groups_users add constraint UK_ewsdo90bf97qmunwue89wq623 unique (users_id);
alter table teachers add constraint UKeoxl6ynhdahri3g5qfrdhflwv unique (username);
alter table teachers add constraint UK4l9jjfvsct1dd5aufnurxcvbs unique (email);
alter table teachers_groups add constraint UK_bikkk1nmvip4n9t9e5njaqdeb unique (groups_id);
alter table tokens add constraint UK_na3v9f8s7ucnj16tylrs822qj unique (token);
alter table users add constraint UKr43af9ap4edm43mmtq01oddj6 unique (username);
alter table users add constraint UK6dotkott2kjsp8vw4d0m25fb7 unique (email);
alter table groups add constraint FKnmyf0spmtdlf9j4rx8el081uc foreign key (teacher_id) references teachers;
alter table groups_users add constraint FKtqn1wd1nl4s87rm85wtcsi763 foreign key (users_id) references users;
alter table groups_users add constraint FKakkv3ihrlmgfjf50vj62a0jr6 foreign key (group_id) references groups;
alter table teachers_groups add constraint FKif7v5iboyedxqh0kql98sojbm foreign key (groups_id) references groups;
alter table teachers_groups add constraint FKdofl7r91qv6ejtv7d4i8ewe13 foreign key (teacher_id) references teachers;
alter table tokens add constraint FKg2u5odybkcjq2fowtslss1mmt foreign key (token_user_id) references users;
alter table user_roles add constraint FKh8ciramu9cc9q3qcqiv4ue8a6 foreign key (role_id) references roles;
alter table user_roles add constraint FKhfh9dx7w3ubf1co1vdev94g3f foreign key (user_id) references users;
alter table users add constraint FKemfuglprp85bh5xwhfm898ysc foreign key (group_id) references groups;