DELETE FROM groups_users;
DELETE FROM user_roles;
DELETE FROM users_groups;
--DELETE FROM admins;
DELETE FROM groups;
--DELETE FROM teachers;
DELETE FROM roles;
DELETE FROM tokens;
DELETE FROM users;
