
--alter table groups drop constraint FKnmyf0spmtdlf9j4rx8el081uc;
--alter table groups drop constraint FKnmyf0spmtdlf9j4rx8el081uc;
--alter table groups_users drop constraint FKtqn1wd1nl4s87rm85wtcsi763;
--alter table groups_users drop constraint FKakkv3ihrlmgfjf50vj62a0jr6;
--alter table teachers_groups drop constraint FKif7v5iboyedxqh0kql98sojbm;
--alter table teachers_groups drop constraint FKdofl7r91qv6ejtv7d4i8ewe13;
--alter table tokens drop constraint FKg2u5odybkcjq2fowtslss1mmt;
--alter table user_roles drop constraint FKh8ciramu9cc9q3qcqiv4ue8a6;
--alter table user_roles drop constraint FKhfh9dx7w3ubf1co1vdev94g3f;
--alter table users drop constraint FKemfuglprp85bh5xwhfm898ysc;

drop table if exists groups_users cascade;
drop table if exists teachers_groups cascade;
drop table if exists user_roles cascade;
drop table if exists admins cascade;
drop table if exists groups cascade;
drop table if exists roles cascade;
drop table if exists teachers cascade;
drop table if exists tokens cascade;
drop table if exists users cascade;
create table admins (id  serial not null, user_creation_date timestamp, email varchar(255), last_visited_date timestamp, password varchar(255), username varchar(255), primary key (id));
create table groups (id  serial not null, teacher_id int4, primary key (id));
create table groups_users (group_id int4 not null, users_id int4 not null, primary key (group_id, users_id));
create table roles (id  serial not null, name varchar(20), primary key (id));
create table teachers (id  serial not null, user_creation_date timestamp, email varchar(255), last_visited_date timestamp, password varchar(255), username varchar(255), primary key (id));
create table teachers_groups (teacher_id int4 not null, groups_id int4 not null, primary key (teacher_id, groups_id));
create table tokens (id  serial not null, token_status boolean, token_creation_date timestamp, token_expiry_date timestamp, token varchar(500) not null, token_user_id int4, primary key (id));
create table user_roles (user_id int4 not null, role_id int4 not null, primary key (user_id, role_id));
create table users (id  serial not null, user_creation_date timestamp, email varchar(255), last_visited_date timestamp, password varchar(255), username varchar(255), group_id int4, primary key (id));
alter table admins add constraint UKmi8vkhus4xbdbqcac2jm4spvd unique (username);
alter table admins add constraint UK47bvqemyk6vlm0w7crc3opdd4 unique (email);
alter table groups_users add constraint UK_ewsdo90bf97qmunwue89wq623 unique (users_id);
alter table teachers add constraint UKeoxl6ynhdahri3g5qfrdhflwv unique (username);
alter table teachers add constraint UK4l9jjfvsct1dd5aufnurxcvbs unique (email);
alter table teachers_groups add constraint UK_bikkk1nmvip4n9t9e5njaqdeb unique (groups_id);
alter table tokens add constraint UK_na3v9f8s7ucnj16tylrs822qj unique (token);
alter table users add constraint UKr43af9ap4edm43mmtq01oddj6 unique (username);
alter table users add constraint UK6dotkott2kjsp8vw4d0m25fb7 unique (email);
alter table groups add constraint FKnmyf0spmtdlf9j4rx8el081uc foreign key (teacher_id) references teachers;
alter table groups_users add constraint FKtqn1wd1nl4s87rm85wtcsi763 foreign key (users_id) references users;
alter table groups_users add constraint FKakkv3ihrlmgfjf50vj62a0jr6 foreign key (group_id) references groups;
alter table teachers_groups add constraint FKif7v5iboyedxqh0kql98sojbm foreign key (groups_id) references groups;
alter table teachers_groups add constraint FKdofl7r91qv6ejtv7d4i8ewe13 foreign key (teacher_id) references teachers;
alter table tokens add constraint FKg2u5odybkcjq2fowtslss1mmt foreign key (token_user_id) references users;
alter table user_roles add constraint FKh8ciramu9cc9q3qcqiv4ue8a6 foreign key (role_id) references roles;
alter table user_roles add constraint FKhfh9dx7w3ubf1co1vdev94g3f foreign key (user_id) references users;
alter table users add constraint FKemfuglprp85bh5xwhfm898ysc foreign key (group_id) references groups;